export type Theme = {
  id: string; name: string;
  layout: 'plain' | 'poster' | 'press' | 'dossier' | 'notebook' | 'cards' | 'studio' | 'terminal' | 'experimental' | 'archive' | 'film' | 'floral' | 'orbit' | 'postcard' | 'botanical' | 'ripple' | 'ribbon';
  category: '极简' | '技术' | '杂志' | '商务' | '生活' | '知识';
  description: string; accent: string; support: string; ink: string; paper: string;
  font: 'sans' | 'serif';
  titleStyle: 'editorial' | 'compact' | 'centered' | 'ruled' | 'edge' | 'plain';
  bodyStyle: 'airy' | 'compact' | 'lead' | 'serif' | 'balanced';
  headingStyle: 'line' | 'bar' | 'pill' | 'boxed' | 'center' | 'underline' | 'number' | 'ribbon' | 'plain' | 'side';
  quoteStyle: 'line' | 'fill' | 'outline' | 'serif' | 'minimal';
  listStyle: 'plain' | 'compact' | 'ruled' | 'boxed' | 'marker';
  tableStyle: 'grid' | 'striped' | 'ledger' | 'minimal' | 'compact';
  codeStyle: 'light' | 'dark' | 'terminal' | 'paper' | 'accent';
  ruleStyle: 'solid' | 'double' | 'dotted' | 'dashed' | 'spaced';
  imageStyle: 'plain' | 'frame' | 'soft' | 'small' | 'wide';
  radius: number; density: number;
};
export const themes: Theme[] = [
{id:'quiet-slate',layout:'plain',name:'静石灰',category:'极简',description:'舒展正文与轻边表格，素标题留出呼吸',accent:'#526078',support:'#b0b8c6',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'plain',quoteStyle:'outline',radius:4,density:1.08,titleStyle:'plain',bodyStyle:'airy',listStyle:'plain',tableStyle:'minimal',codeStyle:'paper',ruleStyle:'spaced',imageStyle:'plain'},
{id:'pine-teal',layout:'plain',name:'松间青',category:'极简',description:'色线章节搭配条纹表格与方点清单',accent:'#2f6b58',support:'#c5a36a',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'line',quoteStyle:'fill',radius:8,density:1,titleStyle:'ruled',bodyStyle:'balanced',listStyle:'marker',tableStyle:'striped',codeStyle:'light',ruleStyle:'solid',imageStyle:'soft'},
{id:'soft-terrace',layout:'studio',name:'暖阶',category:'极简',description:'朱砂细线与大字题头，宽幅配图适合图文故事',accent:'#94613f',support:'#c7b08a',ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'center',quoteStyle:'serif',radius:10,density:1.12,titleStyle:'centered',bodyStyle:'serif',listStyle:'ruled',tableStyle:'minimal',codeStyle:'paper',ruleStyle:'double',imageStyle:'frame'},
{id:'moss-margin',layout:'notebook',name:'苔边',category:'极简',description:'暖白纸面与茶棕标签，便签突出生活片段',accent:'#687340',support:'#cfb771',ink:'#35383e',paper:'#fffdf8',font:'sans',headingStyle:'side',quoteStyle:'minimal',radius:6,density:.92,titleStyle:'compact',bodyStyle:'compact',listStyle:'compact',tableStyle:'compact',codeStyle:'light',ruleStyle:'dotted',imageStyle:'small'},
{id:'cloud-paper',layout:'press',name:'云笺',category:'极简',description:'墨色双线与衬线标题，正文留白适合人文长文',accent:'#4f7084',support:'#b4a88d',ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'underline',quoteStyle:'line',radius:12,density:1.04,titleStyle:'editorial',bodyStyle:'airy',listStyle:'boxed',tableStyle:'ledger',codeStyle:'paper',ruleStyle:'dashed',imageStyle:'wide'},
{id:'terminal-green',layout:'terminal',name:'墨蓝技术',category:'技术',description:'墨蓝模块与深色代码，白底正文适合技术文章',accent:'#365f87',support:'#c4a06b',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'number',quoteStyle:'line',radius:6,density:.94,titleStyle:'compact',bodyStyle:'compact',listStyle:'marker',tableStyle:'ledger',codeStyle:'terminal',ruleStyle:'solid',imageStyle:'frame'},
{id:'blueprint-grid',layout:'dossier',name:'蓝图格',category:'技术',description:'墨蓝题头与资料分区，适合报告和品牌内容',accent:'#376b9b',support:'#aabed1',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'bar',quoteStyle:'fill',radius:4,density:1,titleStyle:'ruled',bodyStyle:'balanced',listStyle:'ruled',tableStyle:'grid',codeStyle:'dark',ruleStyle:'double',imageStyle:'wide'},
{id:'signal-orange',layout:'experimental',name:'电光实验',category:'技术',description:'钴蓝大字、酸橙色块与粗线章节，给观点一个响亮的开场',accent:'#2246e8',support:'#d5ef59',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'boxed',quoteStyle:'minimal',radius:2,density:.9,titleStyle:'editorial',bodyStyle:'compact',listStyle:'boxed',tableStyle:'compact',codeStyle:'accent',ruleStyle:'dotted',imageStyle:'frame'},
{id:'mono-violet',layout:'cards',name:'单色紫',category:'技术',description:'紫藤分组与浅色卡片，适合知识清单和教程',accent:'#69558e',support:'#b8a5c9',ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'pill',quoteStyle:'serif',radius:14,density:1.06,titleStyle:'centered',bodyStyle:'serif',listStyle:'marker',tableStyle:'minimal',codeStyle:'dark',ruleStyle:'spaced',imageStyle:'soft'},
{id:'circuit-black',layout:'terminal',name:'电路墨',category:'技术',description:'墨蓝模块与深色代码，白底正文适合技术文章',accent:'#424f60',support:'#aaa79e',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'side',quoteStyle:'outline',radius:8,density:.88,titleStyle:'plain',bodyStyle:'airy',listStyle:'compact',tableStyle:'striped',codeStyle:'dark',ruleStyle:'dashed',imageStyle:'plain'},
{id:'editorial-wine',layout:'poster',name:'朱砂专题',category:'杂志',description:'双色题头与浅色引言，白底章节适合公众号专题',accent:'#ad403b',support:'#c7a46d',ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'center',quoteStyle:'serif',radius:0,density:1.16,titleStyle:'editorial',bodyStyle:'lead',listStyle:'ruled',tableStyle:'ledger',codeStyle:'paper',ruleStyle:'double',imageStyle:'wide'},
{id:'modern-column',layout:'press',name:'独立报刊',category:'杂志',description:'墨色双线与衬线标题，正文留白适合人文长文',accent:'#444b55',support:'#aa9876',ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'side',quoteStyle:'outline',radius:2,density:1.02,titleStyle:'ruled',bodyStyle:'serif',listStyle:'marker',tableStyle:'minimal',codeStyle:'accent',ruleStyle:'dotted',imageStyle:'frame'},
{id:'copper-ribbon',layout:'poster',name:'铜色飘带',category:'杂志',description:'双色题头与浅色引言，白底章节适合公众号专题',accent:'#9a603f',support:'#c3aa82',ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'ribbon',quoteStyle:'fill',radius:10,density:1.08,titleStyle:'centered',bodyStyle:'airy',listStyle:'boxed',tableStyle:'striped',codeStyle:'paper',ruleStyle:'dashed',imageStyle:'soft'},
{id:'gallery-frame',layout:'studio',name:'人文画册',category:'杂志',description:'朱砂细线与大字题头，宽幅配图适合图文故事',accent:'#a64335',support:'#d4b287',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'boxed',quoteStyle:'minimal',radius:0,density:1.14,titleStyle:'editorial',bodyStyle:'balanced',listStyle:'compact',tableStyle:'grid',codeStyle:'light',ruleStyle:'spaced',imageStyle:'wide'},
{id:'ink-underprint',layout:'archive',name:'纸间档案',category:'杂志',description:'档案签、纸张拼贴与虚线批注，把长文排成值得收藏的纸本',accent:'#833347',support:'#dcc4b6',ink:'#35383e',paper:'#fffaf0',font:'serif',headingStyle:'underline',quoteStyle:'line',radius:4,density:.96,titleStyle:'compact',bodyStyle:'compact',listStyle:'plain',tableStyle:'minimal',codeStyle:'accent',ruleStyle:'solid',imageStyle:'frame'},
{id:'executive-navy',layout:'dossier',name:'深海商务',category:'商务',description:'墨蓝题头与资料分区，适合报告和品牌内容',accent:'#355c81',support:'#bfaa83',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'bar',quoteStyle:'outline',radius:4,density:.92,titleStyle:'ruled',bodyStyle:'balanced',listStyle:'ruled',tableStyle:'grid',codeStyle:'dark',ruleStyle:'solid',imageStyle:'frame'},
{id:'boardroom-umber',layout:'press',name:'会议棕',category:'商务',description:'墨色双线与衬线标题，正文留白适合人文长文',accent:'#7c5d45',support:'#c3ab86',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'number',quoteStyle:'minimal',radius:2,density:.88,titleStyle:'compact',bodyStyle:'compact',listStyle:'compact',tableStyle:'ledger',codeStyle:'paper',ruleStyle:'double',imageStyle:'plain'},
{id:'cobalt-report',layout:'dossier',name:'钴蓝报告',category:'商务',description:'墨蓝题头与资料分区，适合报告和品牌内容',accent:'#3b62a0',support:'#aabdd9',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'boxed',quoteStyle:'fill',radius:6,density:1,titleStyle:'plain',bodyStyle:'balanced',listStyle:'boxed',tableStyle:'striped',codeStyle:'accent',ruleStyle:'dotted',imageStyle:'wide'},
{id:'formal-underline',layout:'plain',name:'签字线',category:'商务',description:'衬线标题和双线分隔营造正式长文节奏',accent:'#7b6748',support:'#c3b794',ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'underline',quoteStyle:'serif',radius:0,density:1.1,titleStyle:'editorial',bodyStyle:'serif',listStyle:'plain',tableStyle:'minimal',codeStyle:'paper',ruleStyle:'double',imageStyle:'frame'},
{id:'clear-agenda',layout:'cards',name:'清晰议程',category:'商务',description:'紫藤分组与浅色卡片，适合知识清单和教程',accent:'#356c72',support:'#a7c2c0',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'pill',quoteStyle:'line',radius:12,density:.96,titleStyle:'centered',bodyStyle:'airy',listStyle:'marker',tableStyle:'compact',codeStyle:'light',ruleStyle:'spaced',imageStyle:'small'},
{id:'sunny-kitchen',layout:'poster',name:'晴日厨房',category:'生活',description:'双色题头与浅色引言，白底章节适合公众号专题',accent:'#b25c35',support:'#d7b878',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'ribbon',quoteStyle:'fill',radius:12,density:1.08,titleStyle:'centered',bodyStyle:'balanced',listStyle:'boxed',tableStyle:'striped',codeStyle:'accent',ruleStyle:'dashed',imageStyle:'soft'},
{id:'garden-note',layout:'notebook',name:'茶棕手记',category:'生活',description:'暖白纸面与茶棕标签，便签突出生活片段',accent:'#8b673e',support:'#c7b58b',ink:'#35383e',paper:'#fffdf8',font:'serif',headingStyle:'center',quoteStyle:'minimal',radius:10,density:1.14,titleStyle:'editorial',bodyStyle:'serif',listStyle:'plain',tableStyle:'minimal',codeStyle:'paper',ruleStyle:'spaced',imageStyle:'frame'},
{id:'weekend-blue',layout:'film',name:'胶片故事',category:'生活',description:'黑色片框、胶片齿孔与暖橙字幕，让生活故事有电影感',accent:'#b8512d',support:'#edc78e',ink:'#35383e',paper:'#fffdf8',font:'sans',headingStyle:'pill',quoteStyle:'outline',radius:14,density:.98,titleStyle:'plain',bodyStyle:'airy',listStyle:'marker',tableStyle:'compact',codeStyle:'light',ruleStyle:'dotted',imageStyle:'wide'},
{id:'coffee-margin',layout:'notebook',name:'咖啡页边',category:'生活',description:'暖白纸面与茶棕标签，便签突出生活片段',accent:'#8a5e45',support:'#d3bba0',ink:'#35383e',paper:'#fffdf8',font:'serif',headingStyle:'side',quoteStyle:'serif',radius:6,density:1.04,titleStyle:'ruled',bodyStyle:'serif',listStyle:'ruled',tableStyle:'ledger',codeStyle:'paper',ruleStyle:'double',imageStyle:'soft'},
{id:'market-fresh',layout:'cards',name:'市集青柠',category:'生活',description:'紫藤分组与浅色卡片，适合知识清单和教程',accent:'#62703e',support:'#c5b98a',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'underline',quoteStyle:'line',radius:8,density:1.12,titleStyle:'compact',bodyStyle:'balanced',listStyle:'boxed',tableStyle:'striped',codeStyle:'accent',ruleStyle:'dashed',imageStyle:'small'},
{id:'study-index',layout:'dossier',name:'研读索引',category:'知识',description:'墨蓝题头与资料分区，适合报告和品牌内容',accent:'#3d6088',support:'#c5ab7d',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'number',quoteStyle:'outline',radius:4,density:.9,titleStyle:'edge',bodyStyle:'compact',listStyle:'marker',tableStyle:'grid',codeStyle:'terminal',ruleStyle:'solid',imageStyle:'frame'},
{id:'learning-lilac',layout:'cards',name:'学思紫',category:'知识',description:'紫藤分组与浅色卡片，适合知识清单和教程',accent:'#69538e',support:'#b8a6c7',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'bar',quoteStyle:'fill',radius:8,density:1,titleStyle:'ruled',bodyStyle:'balanced',listStyle:'ruled',tableStyle:'striped',codeStyle:'dark',ruleStyle:'double',imageStyle:'wide'},
{id:'classical-lesson',layout:'notebook',name:'古典课笺',category:'知识',description:'暖白纸面与茶棕标签，便签突出生活片段',accent:'#84583c',support:'#cbb994',ink:'#35383e',paper:'#fffdf8',font:'serif',headingStyle:'center',quoteStyle:'serif',radius:0,density:1.16,titleStyle:'centered',bodyStyle:'serif',listStyle:'plain',tableStyle:'ledger',codeStyle:'paper',ruleStyle:'spaced',imageStyle:'soft'},
{id:'concept-cards',layout:'cards',name:'灵感卡片',category:'知识',description:'紫藤分组与浅色卡片，适合知识清单和教程',accent:'#6a5298',support:'#b8a5c8',ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'boxed',quoteStyle:'minimal',radius:10,density:.96,titleStyle:'compact',bodyStyle:'compact',listStyle:'boxed',tableStyle:'grid',codeStyle:'light',ruleStyle:'dotted',imageStyle:'frame'},
{id:'reading-ribbon',layout:'poster',name:'阅读飘带',category:'知识',description:'双色题头与浅色引言，白底章节适合公众号专题',accent:'#9c4955',support:'#c7a397',ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'ribbon',quoteStyle:'line',radius:4,density:1.06,titleStyle:'editorial',bodyStyle:'lead',listStyle:'ruled',tableStyle:'minimal',codeStyle:'accent',ruleStyle:'dashed',imageStyle:'wide'},
{ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'center',quoteStyle:'fill',radius:0,density:1.04,titleStyle:'centered',bodyStyle:'airy',listStyle:'plain',tableStyle:'minimal',codeStyle:'paper',ruleStyle:'dotted',imageStyle:'wide',id:'floral-notes',layout:'floral',name:'花笺手绘',category:'生活',description:'淡紫标题与手绘绕圈，浅灰图文块留出轻盈的阅读节奏',accent:'#756cb0',support:'#edc575'},
{ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'plain',quoteStyle:'fill',radius:0,density:1.04,titleStyle:'centered',bodyStyle:'balanced',listStyle:'marker',tableStyle:'grid',codeStyle:'light',ruleStyle:'spaced',imageStyle:'soft',id:'orbit-letter',layout:'orbit',name:'星轨漫游',category:'技术',description:'拱形夜空题头、交叠星轨与星云分区，适合探索与思考',accent:'#435d92',support:'#b5a9df'},
{ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'plain',quoteStyle:'fill',radius:0,density:1.04,titleStyle:'compact',bodyStyle:'balanced',listStyle:'plain',tableStyle:'striped',codeStyle:'paper',ruleStyle:'dashed',imageStyle:'frame',id:'postcard-trip',layout:'postcard',name:'旅行邮简',category:'杂志',description:'邮票齿边、邮戳短线与照片留边，把图文写成一封旅途来信',accent:'#356b85',support:'#d99b6b'},
{ink:'#35383e',paper:'#fffdf7',font:'serif',headingStyle:'plain',quoteStyle:'fill',radius:0,density:1.04,titleStyle:'plain',bodyStyle:'serif',listStyle:'plain',tableStyle:'ledger',codeStyle:'paper',ruleStyle:'dotted',imageStyle:'wide',id:'botanical-journal',layout:'botanical',name:'草木札记',category:'极简',description:'枝叶题签与米色纸面，配图和文字沿细线自然展开',accent:'#44675b',support:'#b98c58'},
{ink:'#35383e',paper:'#ffffff',font:'sans',headingStyle:'plain',quoteStyle:'fill',radius:0,density:1.04,titleStyle:'centered',bodyStyle:'airy',listStyle:'compact',tableStyle:'minimal',codeStyle:'light',ruleStyle:'spaced',imageStyle:'wide',id:'sea-salt',layout:'ripple',name:'海盐波纹',category:'知识',description:'波浪下划线、海蓝小标题与浅蓝图文岛，清爽适合长文',accent:'#2d7184',support:'#8bc7cd'},
{ink:'#35383e',paper:'#ffffff',font:'serif',headingStyle:'plain',quoteStyle:'serif',radius:0,density:1.04,titleStyle:'centered',bodyStyle:'serif',listStyle:'plain',tableStyle:'minimal',codeStyle:'paper',ruleStyle:'solid',imageStyle:'soft',id:'ribbon-letter',layout:'ribbon',name:'丝带来信',category:'商务',description:'双环结、细长飘带与暖粉引言，柔和又有正式的仪式感',accent:'#995260',support:'#d4ae76'},
];
export const categories = ['全部', '极简', '技术', '杂志', '商务', '生活', '知识'] as const;
